# Generated by Django 4.2.2 on 2023-06-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
